[profile.default]
src = 'src'
test = 'test'
out = 'out'
libs = ['node_modules', 'lib']
auto_detect_solc = true
cache = true
#block number
# block_number = 100
# The block timestamp in tests
# block_timestamp = 1500
# allow ffi
ffi = true
# gas limit in tests
gas_limit = 9223372036854775807
# optimizer
optimizer = false
# optimizer runs
# optimizer_runs = 10
optimizer_runs = 1_000_000
# use via-ir optimizer
via_ir = false
fs_permissions = [{ access = "read-write", path = "./"}]
bytecode_hash = "none"
ignored_error_codes = [1878, 2519, 5574,5667,2072,2018,3420, 5740]
evm_version = "london"

[rpc_endpoints]
mainnet = "${MAINNET_URL}"

[fuzz]
# Amount of runs per fuzz test
runs = 1024

[fmt]
line_length = 1000 # This gets overriden by prettier afterwards
tab_width = 4
bracket_spacing = true
int_types = "long"
number_underscore = "thousands"

# See more config options https://github.com/gakonst/foundry/tree/master/config
